### ISSUE TITLE
[Feature]: Result

### ISSUE THREAD

**Issue by shobhit15082003** [OPCODE-Open-Spring-Fest/ballot_block#10]
### So, what is it about?

Create a result function which can be accessed only when the end function is triggered.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SahilMorwal** [comment]
can you assign me this issue

**Comment by MishraSomesh001** [comment]
## Assigned
You are supposed to raise a PR by 28.03.24
