### ISSUE TITLE
[Feature]: Create 2 functions start and end .

### ISSUE THREAD

**Issue by shobhit15082003** [OPCODE-Open-Spring-Fest/ballot_block#4]
### So, what is it about?

Create two functions start and end one . Start function starts the auction and End function ends the auction.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SahilMorwal** [comment]
can you assign me this issue

**Comment by MishraSomesh001** [comment]
##Assigned
You are suppose to submit a pr before 12pm tomorrow i.e 25.03.24.
